### ISSUE TITLE
Openai error when on start

### ISSUE THREAD

**Issue by AbelBlossom** [joshpxyne/gpt-migrate#46]
When running `python main.py --targetlang nodejs` I go this errror

```console
Traceback (most recent call last):
  File "/Users/mac/Desktop/dev/abel/gpt-migrate/gpt_migrate/main.py", line 7, in <module>
    from ai import AI
  File "/Users/mac/Desktop/dev/abel/gpt-migrate/gpt_migrate/ai.py", line 6, in <module>
    from litellm import completion
  File "/Users/mac/Desktop/dev/abel/gpt-migrate/gpt_migrate/env/lib/python3.11/site-packages/litellm/__init__.py", line 28, in <module>
    from .timeout import timeout
  File "/Users/mac/Desktop/dev/abel/gpt-migrate/gpt_migrate/env/lib/python3.11/site-packages/litellm/timeout.py", line 11, in <module>
    from openai.error import Timeout
ModuleNotFoundError: No module named 'openai.error'
```

**Comment by DrSharky** [comment]
I also ran into this problem.

**Comment by prestonator** [comment]
Did you ever find a fix? @DrSharky @AbelBlossom

**Comment by superkido511** [comment]
I fixed it by downgrading openai to 0.28.1. It not perfect but work so far

**Comment by azad-resolver** [comment]
> I fixed it by downgrading openai to 0.28.1. It not perfect but work so far

Thanks, that fixed it for me!
